//! First-party browser terminal assets.
//!
//! The frontend bundle is generated by `make frontend-build` from
//! `apps/server/web`. The binary embeds the built files so production requests do
//! not fetch scripts or styles from a CDN.

use axum::{
    body::Body,
    http::{
        Response, StatusCode,
        header::{CONTENT_TYPE, HeaderValue},
    },
    response::IntoResponse,
};
use rust_embed::Embed;
use termstage_core::security::BasePath;

const INDEX_HTML: &str = include_str!("../web/dist/index.html");
const BASE_HREF_PLACEHOLDER: &str = "<!--TERMSTAGE_BASE_HREF-->";

#[derive(Debug, Embed)]
#[folder = "web/dist/assets/"]
struct EmbeddedAssets;

/// Serves the browser terminal HTML document.
///
/// When `base_path` is set, a `<base href="…/">` element is injected so the
/// document's relative asset and WebSocket URLs resolve against the upstream
/// reverse-proxy prefix instead of the proxied origin's root.
#[must_use]
pub fn index_response(base_path: Option<&BasePath>) -> Response<Body> {
    let body: Body = match base_path {
        Some(prefix) => INDEX_HTML
            .replace(
                BASE_HREF_PLACEHOLDER,
                &format!("<base href=\"{}\">", html_escape_attribute(prefix.as_str())),
            )
            .into(),
        None => Body::from(INDEX_HTML),
    };
    response("text/html; charset=utf-8", body)
}

/// Serves a bundled static asset.
#[must_use]
pub fn asset_response(path: &str) -> Response<Body> {
    if let Some(asset) = EmbeddedAssets::get(path) {
        response(
            content_type_for_path(path),
            Body::from(asset.data.into_owned()),
        )
    } else {
        StatusCode::NOT_FOUND.into_response()
    }
}

fn content_type_for_path(path: &str) -> &'static str {
    let Some(extension) = path.rsplit('.').next() else {
        return "application/octet-stream";
    };
    match extension {
        "css" => "text/css; charset=utf-8",
        "js" => "text/javascript; charset=utf-8",
        "ttf" => "font/ttf",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        _ => "application/octet-stream",
    }
}

fn html_escape_attribute(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for byte in value.bytes() {
        match byte {
            b'&' => out.push_str("&amp;"),
            b'<' => out.push_str("&lt;"),
            b'>' => out.push_str("&gt;"),
            b'"' => out.push_str("&quot;"),
            b'\'' => out.push_str("&#39;"),
            _ => out.push(byte as char),
        }
    }
    out
}

fn response(content_type: &'static str, body: Body) -> Response<Body> {
    let mut response = Response::new(body);
    response
        .headers_mut()
        .insert(CONTENT_TYPE, HeaderValue::from_static(content_type));
    response
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_should_serve_embedded_font_asset() -> anyhow::Result<()> {
        let font_path = EmbeddedAssets::iter()
            .find(|path| path.ends_with(".ttf"))
            .ok_or_else(|| anyhow::anyhow!("embedded nerd font asset"))?;
        let response = asset_response(font_path.as_ref());

        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response
                .headers()
                .get(CONTENT_TYPE)
                .map(HeaderValue::as_bytes),
            Some(b"font/ttf".as_slice()),
        );
        Ok(())
    }

    #[test]
    fn test_should_reject_unknown_embedded_asset() {
        let response = asset_response("../index.js");

        assert_eq!(response.status(), StatusCode::NOT_FOUND);
    }
}
